# Network
MODEL_USE: baseline_wa
HIDDEN_SIZE: 512
FF_SIZE: 2048
DROPOUT_R: 0.1
FLAT_MLP_SIZE: 512
FLAT_GLIMPSES: 1
FLAT_OUT_SIZE: 1024
USE_BBOX_FEAT: False
GPU: '0,1'
WITH_ANSWER: True
WITH_FUSION_LOSS: True
CAP_DIST: 0.3
BETA: 30
ANS_STDDEV: 0.01
PROJ_STDDEV: 0.1
# default values set, no need to change:
# GPU: 0
# WORD_EMBED_SIZE: 300
# FRCN_FEAT_SIZE: (100, 2048)
# BBOX_FEAT_SIZE: (100, 5)
# USE_GLOVE: True
# BATCH_SIZE: 64

# Execution
BATCH_SIZE: 64
LR_BASE: 0.0001
LR_DECAY_R: 0.2
LR_DECAY_LIST: [10, 12]
WARMUP_EPOCH: 3
MAX_EPOCH: 13
GRAD_NORM_CLIP: -1
GRAD_ACCU_STEPS: 1
LOSS_FUNC: bce
LOSS_REDUCTION: sum
OPT: Adam
OPT_PARAMS: {betas: '(0.9, 0.98)', eps: '1e-9'}
