# Network
MODEL_USE: butd
HIDDEN_SIZE: 1024
DROPOUT_R: 0.2
CLASSIFER_DROPOUT_R: 0.5
FLAT_OUT_SIZE: 2048
WITH_ANSWER: True
WITH_FUSION_LOSS: True
LSTM_NUM_DIRECTIONS: 1
LSTM_LAYERS: 1
PROJ_STDDEV: 0.1
ANS_STDDEV: 0.01


# Execution
BATCH_SIZE: 512
LR_BASE: 0.002
LR_DECAY_R: 0.2
LR_DECAY_LIST: [10, 12]
WARMUP_EPOCH: 3
MAX_EPOCH: 13
GRAD_NORM_CLIP: 0.25
GRAD_ACCU_STEPS: 1
LOSS_FUNC: bce
LOSS_REDUCTION: sum
OPT: Adamax
OPT_PARAMS: {betas: '(0.9, 0.999)', eps: '1e-9'}
